apiVersion: v1
kind: ServiceAccount
metadata:
  name: ias
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ias-controller
subjects:
- kind: ServiceAccount
  name: ias
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role
  name: ias-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ias-controller
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch", "extensions"]
  resources: ["*"]
  verbs: ["*"]
